version = 1

exclude_patterns = ["vendor/**"]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/MindHunter86/addie"

[[transformers]]
name = "gofmt"
